image: golang:1.8.3
stages:
  - compile
  - build
services:
    - docker:dind  

before_script:
  - mkdir -p /go/src/omi-gitlab.e-technik.uni-ulm.de/vice/
  - cp -r /builds/vice/vice-worker /go/src/omi-gitlab.e-technik.uni-ulm.de/vice/
  - cd /go/src/omi-gitlab.e-technik.uni-ulm.de/vice/vice-worker

compile:
  stage: compile
  script:
    - go get -d -v ./...
    - go build -v
    - cp vice-worker /builds/vice/vice-worker/
  artifacts:
    paths:
      - vice-worker
      
build:
    stage: build
    image: docker:latest
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:latest    